name: Run E2E Tests
on: 
  - pull_request
  - workflow_dispatch
jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: docker
          POSTGRES_USER: docker
          POSTGRES_DB: academypass
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - run: npm ci
      - run: npm run test:e2e
        env: 
          JWT_SECRET: testing
          DATABASE_URL: "postgresql://docker:docker@localhost:5432/gymtrackrpass?schema=public"
          